apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/moadpy/gitops-repo.git
  username: moadpy
  password: <GITHUB_PAT_PLACEHOLDER>
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/moadpy/app-repo.git
  username: moadpy
  password: <GITHUB_PAT_PLACEHOLDER>
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-rca-root
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/moadpy/gitops-repo.git
    targetRevision: main
    path: clusters/dev/apps
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
